name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TAG_NAME: app
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup image name
        run: echo "IMAGE_NAME=$(echo $TAG_NAME:v1.0.$GITHUB_RUN_NUMBER)" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
        
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{env.IMAGE_NAME}}
          outputs: type=docker,dest=/tmp/docker-image.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/docker-image.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup image name
        run: echo "IMAGE_NAME=$(echo $TAG_NAME:v1.0.$GITHUB_RUN_NUMBER)" >> $GITHUB_ENV
        
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
      - name: Load image
        run: |
          docker load --input /tmp/docker-image.tar
          docker tag ${{env.IMAGE_NAME}} "${{env.DOCKERHUB_USERNAME}}/${{env.IMAGE_NAME}}"
          docker push "${{env.DOCKERHUB_USERNAME}}/${{env.IMAGE_NAME}}"
          
      
    
