name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  TAG_NAME: app

jobs:

  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Setup image name
      run: echo "IMAGE_NAME=$(echo $TAG_NAME:v1.0.$GITHUB_RUN_NUMBER)" >> $GITHUB_ENV
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker build . --file Dockerfile --tag $IMAGE_NAME
        docker save $IMAGE_NAME --output "$IMAGE_NAME.tar"

    - name: Upload Docker image tarball as artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: ${{ github.workspace }}/$IMAGE_NAME.tar
