name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: $GITHUB_REPOSITORY
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build_deploy_run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          LOWERCASE_IMAGE_NAME="${echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]'}"
          docker build . --file Dockerfile --tag ${{LOWERCASE_IMAGE_NAME}}
      
      - name: Save Docker image
        run: |
          docker save $IMAGE_NAME --output "${{ env.IMAGE_NAME }}.tar"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: "${{ env.IMAGE_NAME }}.tar"
          
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Load Docker image
        run: |
          docker load --input "${{ env.IMAGE_NAME }}.tar"

      - name: Set version
        run: |
          VERSION="prod-0.1.${{GITHUB_RUN_NUMBER}}"

      - name: Set image name
        run: |
          IMAGE=${{ secrets.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}

      - name: Tag Docker image
        run: docker tag ${{ env.IMAGE_NAME }} ${{IMAGE}}:${{VERSION}}

      - name: Push Docker image
        run: docker push ${{IMAGE}}:${{VERSION}}

